# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.gidsopenstandaarden.koppelmij
canonical: http://medmij.nl/fhir
url: https://gidsopenstandaarden.github.io/koppelmij-implementation-guide
name: koppelmij-implementation-guide
title: Koppelmij Implementation Guide
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: GPL-3.0-or-later # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: koppelmij
  url: https://github.com/KoppelMij/
  # email: test@example.org
dependencies:
  nictiz.fhir.nl.r4.zib2020:
    version: 0.11.0-beta.1
    uri: http://simplifier.net/packages/nictiz.fhir.nl.r4.zib2020#0.11.0-beta.1
  nictiz.fhir.nl.r4.nl-core:
    version: 0.11.0-beta.1
    uri: http://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core#0.11.0-beta.1

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
# dependencies:
#   nictiz.fhir.nl.r4.nl-core:
#     id: nlcore
#     uri: https://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core
#     version: 0.10.0-beta.1
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
# pages:
#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:

pages:
  index.md:
    title: Home
  overview.md:
    title: Overview
  koppelmij_option_1.md:          # ← merged 1a & 1b → 1
    title: Option 1 - OTP via OIDC /authorize
  koppelmij_option_2a.md:
    title: Option 2a - PGO als SMART on FHIR Resource Service
  koppelmij_option_2b.md:
    title: Option 2b - PGO als SMART on FHIR Authorization Server met Module Token Exchange
  koppelmij_option_3a.md:
    title: Option 3a - Token Exchange Launch Token met Gebruikersidentificatie
  koppelmij_option_3b.md:
    title: Option 3b - DVA-geïnitieerde Module Launch met SMART on FHIR
  overwegingen_optie_3a.md:
    title: Overwegingen voor keuze Optie 3a
  koppeltaal_domeinen.md:
    title: Koppeltaal Domeinen in de context van KoppelMij
  harde_zachte_vereisten.md:
    title: Harde en Zachte Vereisten
  module_terugkeer.md:
    title: Terugkeren na Module Afsluiten
  comparison_option2_a_b.md:
    title: 2a en 2b
  oidc_mobile_sso_explanation.md:
    title: OpenID Connect Native SSO voor Mobiele Apps 1.0
  authorization-patient.md:
    title: Autorisatie Patient
  authorization-practitioner.md:
    title: Autorisatie Practitioner
  authorization-relatedperson.md:
    title: Autorisatie RelatedPerson


#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
# parameters:
#   excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Overview:
    Overview: overview.html
  Solution Design:
    Token Exchange met Gebruikersidentificatie: koppelmij_option_3a.html
  Overwegingen:
    Keuze voor Optie 3a: overwegingen_optie_3a.html
    Koppeltaal Domeinen: koppeltaal_domeinen.html
    Harde en Zachte Vereisten: harde_zachte_vereisten.html
    Module Terugkeer: module_terugkeer.html
  KoppelMij FHIR Resources:
    Profile - Task: StructureDefinition-MedMij-Task.html
    Profile - ActivityDefinition: StructureDefinition-MedMij-ActivityDefinition.html
    Profile - Endpoint: StructureDefinition-MedMij-Endpoint.html
    Profile - Device: StructureDefinition-KT2Device.html
    Extension - Resource Origin: StructureDefinition-resource-origin.html
    Extension - Endpoint Extension: StructureDefinition-KT2EndpointExtension.html
    Extension - Publisher Id: StructureDefinition-KT2PublisherId.html
    Extension - Correlation Id: StructureDefinition-correlation-id.html
    Extension - Request Id: StructureDefinition-request-id.html
    Extension - Trace Id: StructureDefinition-trace-id.html
    Extension - Instantiates: StructureDefinition-instantiates.html
    Example Scenario 1 (COPD) - Task - Van Duinen: Task-KoppelMij-Task-Questionnaire-Van-Duinen.html
    Example Scenario 1 (COPD) - Task Update - Van Duinen: Task-KoppelMij-Task-Update-Questionnaire-Van-Duinen.html
    Example Scenario 1 (COPD) - ActivityDefinition - COPD: ActivityDefinition-KoppelMij-ActivityDefinition-COPD-Questionnaire.html
    Example Scenario 1 (COPD) - Endpoint - COPD: Endpoint-KoppelMij-Endpoint-Vragenlijst-COPD.html
    Example Scenario 1 (COPD) - Patient - Van Duinen: Patient-KoppelMij-Patient-Van-Duinen.html
    Example Scenario 1 (COPD) - PractitionerRole - De Haard: PractitionerRole-KoppelMij-PractitionerRole-De-Haard.html
    Example Scenario 1 (COPD) - Practitioner - De Haard: Practitioner-KoppelMij-Practitioner-De-Haard.html
    Example Scenario 1 (COPD) - Organization - Medrie: Organization-KoppelMij-Organization-Huisartsenpraktijk-Medrie.html
    Example Scenario 2 (Angststoornis) - Task - De Groot: Task-KoppelMij-Task-Questionnaire-De-Groot.html
    Example Scenario 2 (Angststoornis) - ActivityDefinition - Angststoornis: ActivityDefinition-KoppelMij-ActivityDefinition-Angststoornis-Questionnaire.html
    Example Scenario 2 (Angststoornis) - Endpoint - Angststoornis: Endpoint-KoppelMij-Endpoint-Vragenlijst-Angststoornis.html
    Example Scenario 2 (Angststoornis) - Patient - De Groot: Patient-KoppelMij-Patient-De-Groot.html
    Example Scenario 2 (Angststoornis) - PractitionerRole - Vonk: PractitionerRole-KoppelMij-PractitionerRole-Vonk.html
    Example Scenario 2 (Angststoornis) - Practitioner - Vonk: Practitioner-KoppelMij-Practitioner-Vonk.html
    Example Scenario 2 (Angststoornis) - Organization - GGZ: Organization-KoppelMij-Organization-GGZ.html
  Uitleg:
    OpenID Connect Native SSO voor Mobiele Apps 1.0: oidc_mobile_sso_explanation.html
  Archief:
    Option 1: koppelmij_option_1.html
    Option 2a: koppelmij_option_2a.html
    Option 2b: koppelmij_option_2b.html
    Option 3b: koppelmij_option_3b.html


