# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.gidsopenstandaarden.koppelmij
canonical: https://gidsopenstandaarden.github.io/koppelmij-implementation-guide
url: https://gidsopenstandaarden.github.io/koppelmij-implementation-guide
name: koppelmij-implementation-guide
title: Koppelmij Implementation Guide
# description: Example Implementation Guide for getting started with SUSHI
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2024+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
license: GPL-3.0-or-later # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: gidsopenstandaarden
  url: https://www.gidsopenstandaarden.org
  # email: test@example.org

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
# dependencies:
#   nictiz.fhir.nl.r4.nl-core:
#     id: nlcore
#     uri: https://simplifier.net/packages/nictiz.fhir.nl.r4.nl-core
#     version: 0.10.0-beta.1
#
# dependencies:
#   hl7.fhir.us.core: 3.1.0
#   hl7.fhir.us.mcode:
#     id: mcode
#     uri: http://hl7.org/fhir/us/mcode/ImplementationGuide/hl7.fhir.us.mcode
#     version: 1.0.0
#
#
# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
# The page file name is used as the key. If title is not provided,
# then the title will be generated from the file name.  If a
# generation value is not provided, it will be inferred from the
# file name extension.  Any subproperties that are valid filenames
# with supported extensions (e.g., .md/.xml) will be treated as
# sub-pages.
#
# pages:
#   index.md:
#     title: Example Home
#   implementation.xml:
#   examples.xml:
#     title: Examples Overview
#     simpleExamples.xml:
#     complexExamples.xml:

pages:
  index.md:
    title: Home
  overview.md:
    title: Overview
  koppelmij_option_1.md:          # ← merged 1a & 1b → 1
    title: Option 1 - OTP via OIDC /authorize
  koppelmij_option_2a.md:
    title: Option 2a - PGO als SMART on FHIR Resource Service
  koppelmij_option_2b.md:
    title: Option 2b - PGO als SMART on FHIR Authorization Server met Module Token Exchange
  koppelmij_option_3a.md:
    title: Option 3a - Token Exchange Launch Token met Gebruikersidentificatie
  koppelmij_option_3b.md:
    title: Option 3b - DVA-geïnitieerde Module Launch met SMART on FHIR
  overwegingen_optie_3a.md:
    title: Overwegingen voor keuze Optie 3a
  harde_zachte_vereisten.md:
    title: Harde en Zachte Vereisten
  comparison_option2_a_b.md:
    title: 2a en 2b
  oidc_mobile_sso_explanation.md:
    title: OpenID Connect Native SSO voor Mobiele Apps 1.0


#
#
# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
# For parameters defined by core FHIR see:
# http://build.fhir.org/codesystem-guide-parameter-code.html
# For parameters defined by the FHIR Tools IG see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
#
# parameters:
#   excludettl: true
#   validation: [allow-any-extensions, no-broken-links]
#
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Overview:
    Overview: overview.html
  Solution Design:
    Token Exchange met Gebruikersidentificatie: koppelmij_option_3a.html
  Overwegingen:
    Keuze voor Optie 3a: overwegingen_optie_3a.html
    Harde en Zachte Vereisten: harde_zachte_vereisten.html
  Uitleg:
    OpenID Connect Native SSO voor Mobiele Apps 1.0: oidc_mobile_sso_explanation.html
  Archief:
    Option 1: koppelmij_option_1.html
    Option 2a: koppelmij_option_2a.html
    Option 2b: koppelmij_option_2b.html
    Option 3b: koppelmij_option_3b.html


