@startuml DVA_Process_Flow
!theme plain
skinparam backgroundColor white
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam maxMessageSize 200

participant "Browser" as BR
participant "PGO" as PGO
participant "DVA" as DVA
participant "Module" as MOD

title DVA Proces Flow - OIDC voor otp_token

group Initiële Verzameling
PGO -> DVA : Verzamelen gegevens
DVA -> BR: DigID
DVA --> PGO : Krijgt access_token
end

group PGO Start Launch via DVA
note over PGO, DVA : OIDC Flow

PGO -> DVA : /authorize\n(response_type=code)\n(front channel)
DVA -> BR : Zet kort-geldige cookie\n(gebonden aan otp_token)
DVA --> PGO : Authorize response

PGO -> DVA : /token\n(backchannel)
DVA --> PGO : Token response\n(met oa otp_token)
end

group Launch naar Module
PGO -> MOD : Launch met otp_token
end

group Module Start SMART on FHIR flow
note over MOD, DVA : SMART on FHIR flow

MOD -> DVA : /authorize\n(launch=otp_token)\n(front channel)
DVA -> BR : Correleer otp_token\nmet browser cookie
DVA --> MOD : Authorize response

MOD -> DVA : /token\n(backchannel)
DVA --> MOD : Token response\n(met access_token)
end

note over PGO, MOD : Module kan nu functioneren\nmet geauthenticeerde browser

@enduml
