@startuml
actor "Zorgverlener" as zv
actor "Cliënt" as client
boundary "PGO (Persoonlijke Gezondheidsomgeving)" as pgo
boundary "ECD Applicatie" as ecd
control "FHIR zorg Aanbieder (DVA)" as za
boundary "IdP van Zorg Aanbieder" as idp
actor "Module Aanbieder" as module

group zorgverlener start
  zv -> ecd: login applicatie
  ecd <-> zv: authenticatie (eigen login mechanisme)
  ecd -> za: ophalen ActivityDefinitions
  za --> ecd: ActivityDefinitions
  ecd --> zv: toon ActivityDefinitions
end

group toewijzen interventie
  zv -> ecd: selecteer ActivityDefinition voor cliënt
  zv -> ecd: wijs ActivityDefinition toe aan cliënt
  ecd -> za: creëer Task (gebaseerd op ActivityDefinition)
  za --> ecd: bevestiging Task aangemaakt
  ecd --> zv: bevestiging toewijzing
  zv -> client: notificatie over opdracht (papier/mail)
end

group cliënt start
  client -> pgo: aanmelden/inloggen PGO
  pgo -> za: ophalen
  za -> idp: /authorize
  idp <-> client: login
  idp --> za: id_token, access_token
  za --> pgo: toegewezen Tasks
  pgo --> client: view toegewezen Tasks
end

group launch interventie
  client -> pgo: selecteer Task
  pgo -> module: launch (Task, FHIR service)
  module -> za: get ./well-known/smart-configuration
  module -> module: extract smart-configuration['authorization_endpoint']
  module -> idp: /authorize
  idp <-> client: login bij module (SSO)
  idp --> module: id_token, access_token
  module -> za: get Task
  za --> module: Task
end

group uitvoeren interventie
  module <-> client: uitvoeren van interventie
  module -> za: update Task status

  alt notify
    za -> pgo: notify Task update
    za -> ecd: notify Task update
  end
end

group volgen interventie zorgverlener
  zv -> ecd: vraag status op
  ecd -> za: haal Task op
  za --> ecd: Task
  ecd --> zv: toon status interventie
end

group volgen interventie cliënt
  client -> pgo: bekijk status
  pgo -> za: vraag status op
  za -> idp: /authorize
  idp <-> client: login (SSO)
  idp --> za: id_token, access_token
  za --> pgo: Task
  pgo --> client: view status
end

group inzien status zorgverlener
  zv -> ecd: vraag status interventie
  ecd -> za: haal Task op
  za --> ecd: Task
  ecd --> zv: toon status
end

group inzien status cliënt
  client -> pgo: bekijk status
  pgo -> za: ophalen
  za -> idp: /authorize
  idp <-> client: login (SSO)
  idp --> za: id_token, access_token
  za -> za: haal Task op
  za --> pgo: Task
  pgo --> client: view status
end
@enduml
